language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8.3
      brew_packages: v8@3.15
      latex: false
    - os: osx
      osx_image: xcode8
      disable_homebrew: true
      latex: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - libv8-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi